# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on PR to main
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: $GITHUB_WORKSPACE
    steps:
      - uses: actions/checkout@v3
      - name: "Retrieve dependencies"
        run: |
          echo ${{ github.head_ref }}
          pip install -r requirements.txt
      - name: "Test Marshall's assignments"
        if: ${{ github.head_ref == 'refs/heads/marshall-assignments' }}
        run: python marshall-solutions/most_common_element_impl.py
      - name: "Test Ronan's assignments"
        if: ${{ github.head_ref == 'refs/heads/ronan-assignments' }}
        run: python ronan-solutions/most_common_element_impl.py
      - name: Run project tests
        run: pytest
